/** Emits the generated JSON bundle (for the app) and seed.sql (for Supabase). */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type {
  ContentManifest,
  Movement,
  Path,
  Program,
} from "./schema.ts";

const HEADER =
  "// GENERATED by @the-stead/content-pipeline — do not edit by hand.\n" +
  "// Source: data/progressions/*.yaml + content/*. Run `npm run content:build`.\n";

export async function emitJson(
  outDir: string,
  programs: Program[],
  movements: Movement[],
  manifest: ContentManifest,
): Promise<void> {
  await mkdir(outDir, { recursive: true });
  const write = (name: string, data: unknown) =>
    writeFile(path.join(outDir, name), `${JSON.stringify(data, null, 2)}\n`, "utf8");
  await Promise.all([
    write("programs.json", programs),
    write("movements.json", movements),
    write("manifest.json", manifest),
  ]);
  // A README so the generated dir isn't mistaken for hand-authored source.
  await writeFile(
    path.join(outDir, "README.md"),
    `${HEADER}\nThese files are generated. Edit the YAML/Markdown sources and rebuild.\n`,
    "utf8",
  );
}

// --- SQL emission ----------------------------------------------------------

function q(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function n(value: number | null | undefined): string {
  return value === null || value === undefined ? "null" : String(value);
}

function b(value: boolean | undefined): string {
  return value === undefined ? "null" : value ? "true" : "false";
}

function textArray(values: string[]): string {
  return `array[${values.map((v) => q(v)).join(", ")}]::text[]`;
}

function intArray(values: number[]): string {
  return `array[${values.join(", ")}]::int[]`;
}

/** Builds an idempotent multi-row upsert for one table. */
function upsert(
  table: string,
  columns: string[],
  rows: string[][],
  conflictKey = "id",
): string {
  if (rows.length === 0) return "";
  const updates = columns
    .filter((c) => c !== conflictKey)
    .map((c) => `${c} = excluded.${c}`)
    .join(", ");
  const valueRows = rows.map((r) => `  (${r.join(", ")})`).join(",\n");
  return (
    `insert into ${table} (${columns.join(", ")}) values\n${valueRows}\n` +
    `on conflict (${conflictKey}) do update set ${updates};\n`
  );
}

export async function emitSeed(
  outPath: string,
  programs: Program[],
  movements: Movement[],
): Promise<void> {
  const programRows: string[][] = [];
  const blockRows: string[][] = [];
  const dayRows: string[][] = [];
  const itemRows: string[][] = [];
  const movementRows: string[][] = [];

  for (const mv of movements) {
    movementRows.push([
      q(`${mv.tierSlug}-${mv.slug}`),
      q(mv.tierSlug),
      q(mv.pattern),
      q(mv.slug),
      q(mv.name),
      q(mv.tag),
      q(mv.body),
    ]);
  }

  for (const program of programs) {
    programRows.push([
      q(program.tierSlug),
      q(program.tier),
      q(program.title),
      n(program.weeks.length),
      textArray(program.paths),
      q(program.optionalDays ?? null),
    ]);

    for (const block of program.blocks) {
      blockRows.push([
        q(`${program.tierSlug}-b${block.number}`),
        q(program.tierSlug),
        n(block.number),
        q(block.name),
        intArray(block.weeks),
      ]);
    }

    for (const week of program.weeks) {
      for (const day of week.days) {
        for (const path_ of Object.keys(day.prescriptions) as Path[]) {
          const items = day.prescriptions[path_] ?? [];
          const dayId = `${program.tierSlug}-w${week.week}-d${day.day}-${path_}`;
          dayRows.push([
            q(dayId),
            q(program.tierSlug),
            n(week.week),
            n(day.day),
            q(path_),
            q(day.title),
            q(day.kind),
            q(day.duration),
            q(day.note),
          ]);
          for (const item of items) {
            const movementId = item.movementSlug
              ? `${program.tierSlug}-${item.movementSlug}`
              : null;
            itemRows.push([
              q(`${dayId}-${item.orderIdx}`),
              q(dayId),
              n(item.orderIdx),
              q(movementId),
              q(item.rawText),
              q(item.kind),
              n(item.sets),
              n(item.repLow),
              n(item.repHigh),
              n(item.durationSec),
              n(item.distanceM),
              b(item.perSide),
              q(item.loadHint ?? null),
              q(item.note ?? null),
            ]);
          }
        }
      }
    }
  }

  const sql =
    "-- GENERATED by @the-stead/content-pipeline — do not edit by hand.\n" +
    "-- Idempotent: re-runnable upserts. Apply after the schema migrations.\n" +
    "-- Note: removed source lines are not pruned here; content edits in place.\n\n" +
    "begin;\n\n" +
    upsert(
      "programs",
      ["slug", "tier", "title", "length_weeks", "paths", "optional_days"],
      programRows,
      "slug",
    ) +
    "\n" +
    upsert(
      "blocks",
      ["id", "program_slug", "number", "name", "weeks"],
      blockRows,
    ) +
    "\n" +
    upsert(
      "movements",
      ["id", "program_slug", "pattern", "slug", "name", "tag", "body_md"],
      movementRows,
    ) +
    "\n" +
    upsert(
      "program_days",
      [
        "id",
        "program_slug",
        "week",
        "day",
        "path",
        "title",
        "kind",
        "duration_label",
        "note",
      ],
      dayRows,
    ) +
    "\n" +
    upsert(
      "prescribed_items",
      [
        "id",
        "program_day_id",
        "order_idx",
        "movement_id",
        "raw_text",
        "kind",
        "sets",
        "rep_low",
        "rep_high",
        "duration_sec",
        "distance_m",
        "per_side",
        "load_hint",
        "note",
      ],
      itemRows,
    ) +
    "\ncommit;\n";

  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFile(outPath, sql, "utf8");
}
